import Auth from "./auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootTemplate({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Auth />
      <div className="mb-5 text-center">{children}</div>
    </>
  );
}
